### ISSUE TITLE
Stale block address indexing bug

### ISSUE THREAD

**Issue by mononaut** [mempool/electrs#11]
Electrs appears to double-count certain transactions during address indexing, which produces incorrect chain stats (`funded_txo_sum` etc) and therefore incorrect balances displayed on mempool.space.

<img width="539" alt="Screenshot 2023-06-05 at 11 39 08 AM" src="https://github.com/mempool/electrs/assets/83316221/cdbf854c-b78e-489f-837d-1cb98c7e592f">

---

Specifically, the error seems to occur when a transaction is included in a stale block, but *not* the "winning" block at the same height.

For example, transaction [3738...e88e](https://mempool.space/tx/3738b0795522795d50fe9c385154abbb41585d425a402c9979db20758ba9e88e
)
was included in a recent stale block 000000000000000000032956cbfd8721abe0572d81542e75e38e6185312bee09 at height 792379, but eventually entered the main chain in block [792380](https://mempool.space/block/792380).

The transaction is then double-counted during address indexing, 
causing address [132kFhZzkFytWAefWy7nCYgJHcU84RjJNa
](https://mempool.space/address/132kFhZzkFytWAefWy7nCYgJHcU84RjJNa
) to show a negative balance.

Similarly, transaction [3264...d9cb](https://mempool.space/tx/326458888709874443396dc5f66eb359cd59e7984dcc0778b64d126cf0b2d9cb) appears in the same stale block, enters the main chain in block [792382](https://mempool.space/block/792382), and is counted twice towards address [bc1qzuupxjkwv4dj69m3xzack5sdqtacn6l8czndlf](https://mempool.space/address/bc1qzuupxjkwv4dj69m3xzack5sdqtacn6l8czndlf), causing a positive balance to display when in fact the address should be empty.

<img width="858" alt="Screenshot 2023-06-05 at 12 05 33 PM" src="https://github.com/mempool/electrs/assets/83316221/caa88c6f-98dd-4930-b920-fa2a726d4740">

---

Transactions which appear at the *same* height on both sides of a chain split appear to be handled correctly.

For example, address [bc1pfajpg0fp0a62wjrax682hkzvrczxx7j3htrtm0ae6cnx72ye2rnscarxrp](https://mempool.space/address/bc1pfajpg0fp0a62wjrax682hkzvrczxx7j3htrtm0ae6cnx72ye2rnscarxrp) has a transaction which is included in both versions of block 792379, but reports the correct balance.

**Comment by mononaut** [comment]
As seen in https://github.com/mempool/mempool/issues/4196, this still seems to be reproducing in production on multiple servers in all sites, e.g.

https://node203.fra.mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx
https://node204.tk7.mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx
https://node202.fmt.mempool.space/address/38A4VFuFs95QaxTPUec9jEVqW5rFE7z7jx

<img width="793" alt="Screenshot 2023-08-25 at 1 47 40 AM" src="https://github.com/mempool/electrs/assets/83316221/99ce6732-7389-402e-a7c5-247584412462">

In this case transaction [20f7...3e8c](20f7dfc344ec702df4602bcd8cc720ebee5571174e0e65200542bdc2a87a3e8c) was included in that same stale block at height 792379, and again in the main chain in block [792380](https://mempool.space/block/792380), and so counted twice towards the address totals.

**Comment by junderw** [comment]
The solution is #28 

Which I'm currently working on.
