### ISSUE TITLE
block difficulty value is integer instead of floating point

### ISSUE THREAD

**Issue by wiz** [mempool/electrs#3]
Moved from https://github.com/Blockstream/esplora/issues/370

### How to Reproduce
https://blockstream.info/api/block/000000006e082edaab177e74a7cc0db2a6b908812ae801d535e0f2033aa8657d

### Expected Value
  "difficulty": 1.182899534312841,

## Actual Value
"difficulty":1

**Comment by wiz** [comment]
@junderw my understanding is that the problem is within rust-bitcoin returning an int instead of a float for the difficulty - you might have to fork that project as well (or submit a PR)

**Comment by junderw** [comment]
It's much more difficult than just any old int.

rust-bitcoin created a special 256 bit int type (since primitive types in Rust only go up to 128 bit), so it's not so easy to convert to f64...

I'll bring up an issue.

**Comment by Kixunil** [comment]
@wiz no need for extreme options such as forking projects, we at rust-bitcoin are happy to accept/implement reasonable requests such as this one. :)
