### ISSUE TITLE
question: upgrade path from Blockstream/electrs?

### ISSUE THREAD

**Issue by guggero** [mempool/electrs#52]
Hi all

Sorry for creating an issue with just a question, but the discussions section isn't enabled in this project.
Feel free to close immediately if you think I should ask somewhere else.

My question is: I'm currently running the https://github.com/Blockstream/electrs fork of `electrs`, but would like to upgrade to this one. Can I directly start using a docker image based on this fork or do I need to do a full re-index?

Thanks!

**Comment by junderw** [comment]
I don't believe we've made any re-index requiring changes yet.

**Comment by guggero** [comment]
Okay, thank you. I guess I'll just try out upgrading and report back if anything doesn't seem to work.
