### ISSUE TITLE
Crash with error message: Too many open files

### ISSUE THREAD

**Issue by kiennd** [mempool/electrs#69]
Dear Team,
I ran on ubuntu and got bellow message:

```
thread 'blkfiles_reader-3' panicked at 'failed to read "/root/.bitcoin/blocks/blk00008.dat": Os { code: 24, kind: Uncategorized, message: "Too many open files" }', src/new_index/fetch.rs:159:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

config:

`Config { log: StdErrLog { verbosity: Error, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Auto }, network_type: Bitcoin, db_path: "./db/mainnet", daemon_dir: "/root/.bitcoin", blocks_dir: "/root/.bitcoin/blocks", daemon_rpc_addr: 127.0.0.1:8332, electrum_rpc_addr: 127.0.0.1:50001, http_addr: 0.0.0.0:5500, http_socket_file: None, rpc_socket_file: None, monitoring_addr: 0.0.0.0:4224, jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: None, precache_scripts: None, precache_threads: 16, utxos_limit: 300000, electrum_txs_limit: 500, electrum_banner: "Welcome to mempool-electrs 3.0.0-dev-b379d24", mempool_backlog_stats_ttl: 10, mempool_recent_txs_size: 10, rest_default_block_limit: 10, rest_default_chain_txs_per_page: 25, rest_default_max_mempool_txs: 50, rest_max_mempool_page_size: 1000 }`

version: mempool-electrs 3.0.0-dev-b379d24
Thank you in advance.

**Comment by junderw** [comment]
This is outside of the scope of this application.

On linux, please use `ulimit -n` to modify your process's maximum number of open file descriptors.

See the man pages for ulimit for details: https://ss64.com/bash/ulimit.html

We recommend `ulimit -n 1000000` if possible (1 million)

**Comment by kiennd** [comment]
thank you, let me try
