### ISSUE TITLE
Access to blk files

### ISSUE THREAD

**Issue by RooSoft** [mempool/electrs#76]
I see that this version of electrs needs to have read access to .bitcoin/blocks/*.blk files.

Thing is, Bitcoin Core creates them with 600 rights. Because of this, the only user that technically has access those files, is Bitcoin Core's user itself.

Is this app designed to be run with Bitcoin Core's user?

Is there a more secure way to execute it?

**Comment by junderw** [comment]
It only uses the blockfiles for the initial sync. Once you've fully synced once, it won't access the files again.

But yes, it does need access to the files.
